"""Reproducible reporting: validation table, figures and benchmarks.

The ``scripts/`` entry points and the ``mcengine`` CLI are thin wrappers around this
package, so every number in the README and the docs is regenerated by one command.
"""

from __future__ import annotations
